version: '3.1'

services:
  mongo_one:
    container_name: mongo-1
    image: mongo
    command: mongod --replSet my-mongo-set
    ports:
      - '30001:27017'
    networks:
      - webnet

  mongo_two:
    container_name: mongo-2
    image: mongo
    command: mongod --replSet my-mongo-set
    ports:
      - '30002:27017'
    networks:
      - webnet

  mongo_three:
    container_name: mongo-3
    image: mongo
    command: mongod --replSet my-mongo-set
    ports:
      - '30003:27017'
    networks:
      - webnet

  mongo_four:
    container_name: mongo-4
    image: mongo
    command: mongod --replSet my-mongo-set
    ports:
      - '30004:27017'
    networks:
      - webnet

networks:
  webnet:
