version: '3'
services:
  orders_services:
    image: randyma01/containerhapi3
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - '4000:80'
    networks:
      - webnets
networks:
  webnet:
