version: '3'

services:

  catalog_services:
    container_name: catalog_services
    image: randyma01/catalog_services:v2.0.0
    depends_on:
      - 'mongo'
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - '7000:8080'
    networks:
      - webnets
  
  orders_services:
      container_name: orders_service
      image: randyma01/orderservices:v2.0.0
      depends_on:
      - 'mongo'
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - '7001:8080'
    networks:
      - webnets

  mongodb:
    image: mongo
    ports: 
      - '27017:27017'
    volumes:
      - "/home/docker/data:/data"
    networks: 
      - backend
    commands: mongod --replSet rs0
  
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "80:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

networks:
  webnet:
    driver: overlay    

