version: "3"
services:
  nginx:
    image: nginx
    ports:
        - "8080:8080"
    volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
    deploy:
      placement:
        constraints: [node.role == manager]
    depends_on:
        - orders
        - visualizer
  orders:
    depends_on:
        - nginx
    image: brmasis/compratec:orders-service
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports: 
        - "3001:3000"
  visualizer:
      image: dockersamples/visualizer:stable
      ports:
        - "8081:8080"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      deploy:
        placement:
          constraints: [node.role == manager]
networks:
  webnet: