version: '3'

services:
  users_services:
    container_name: "users-servive"
    image: users_service:v1
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - '7000:8000'
    networks:
      - db_net

networks:
  db_net:
